version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ranks-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wt46tlbs4xhh"
s3_prefix = "ranks-sam"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
